# Generated by Django 6.0.5 on 2026-06-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
